# Generated by Django 4.0.6 on 2022-07-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
